### ISSUE TITLE
Timestamps on Startup

### ISSUE THREAD

**Issue by stuwilkins** [areaDetector/ADProsilica#11]
Hi, 

From my use of the prosilica there seems to be some inconsistencies and problems with the timestamping. I noticed that on IOC start the timestamps are not correct and this is probably do the fact that the camera is not "synchronized" with the IOC and the function ```prosilica::syncTimer()``` is not called on startup which means that ```lastSyncTime``` is uninitialized. 

I would suggest that on successful connection that ```prosilica::syncTimer()``` is called to ensure that the camera and IOC can give reliable timestamps. 

Also, while I know that it might be too late to change defaults, I think that the default for the timestamps should be ```PSTimestampTypePOSIX``` as this is more likely the intended use. Unless someone really wants to do something like XPCS and need a vary accurate interval timer then I am not sure of the utility of the other options in the majority of uses. 

It is also unclear to me that if the TSE field is set to -2 what happens if timestamping is set to using the "native tics" ... But I haven't had a chance to test. 

Any thoughts @MarkRivers? I would be happy to make these changes and do a PR, but before hand would like to do something which is consistent and useful!

**Comment by MarkRivers** [comment]
Hi Stuart,
The timestamp support was done by Jason Abernathy when he was student at Univ. of Victoria.  I accepted his changes but have not really tested them.  I would be happy to have you test and make changes that you think make sense.

**Comment by stuwilkins** [comment]
Ok let me do that …. Thanks!

**Comment by stuwilkins** [comment]
Fixed in #14.
